### ISSUE TITLE
inst_uncertain.* should be named to match existing convention

### ISSUE THREAD

**Issue by phillipstanleymarbell** [physical-computation/sunflower-simulator#135]
inst_uncertain.* should be named to match existing convention (e.g., uncertain-upe.*). After #132 has been merged. @harrysarson, are you able to take care of this?

**Comment by harrysarson** [comment]
I should be able to take a look at this and fix it soon 🙂 

For background, during my work on uncertainty I started by implementing a library and then moved to a hardware level design. The naming style of the functions reflect the fact that they simulate uncertainty propagation at the instruction level rather than at software level.

At some point there were `lib_uncertain.` functions which gave the naming convention more sense.
